// frontend/src/components/InsightCard.tsx
import type { Insight } from "../types";

interface Props {
  studentName: string;
  insight: Insight | null;
  loading: boolean;
  error: string | null;
  onGenerate: () => void;
}

export default function InsightCard({ studentName, insight, loading, error, onGenerate }: Props) {
  return (
    <div className="rounded-xl border border-indigo-200 bg-white p-5 shadow-sm">
      <div className="flex items-center justify-between">
        <h2 className="font-semibold">AI insight</h2>
        <button
          onClick={onGenerate}
          disabled={loading}
          className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700 disabled:opacity-60"
        >
          {loading ? "Analysing…" : insight ? "Regenerate" : `Generate insight for ${studentName}`}
        </button>
      </div>

      {error && <p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
      {!insight && !loading && !error && (
        <p className="mt-3 text-sm text-slate-500">
          The AI explains the computed risk factors and recommends an action.
        </p>
      )}

      {insight && (
        <div className="mt-4 space-y-3 text-sm">
          <Block label="Why" text={insight.why} />
          <Block label="Primary concern" text={insight.primary_concern} />
          <Block label="Recommended action" text={insight.recommended_action} highlight />
          <p className="text-xs text-slate-400">
            {insight.source === "ai" ? "Generated by AI" : "Rule-based fallback (AI unavailable)"}
            {insight.cached ? " · cached" : ""}
          </p>
        </div>
      )}
    </div>
  );
}

function Block({ label, text, highlight }: { label: string; text: string; highlight?: boolean }) {
  return (
    <div className={highlight ? "rounded-lg bg-indigo-50 p-3" : ""}>
      <p className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</p>
      <p className="mt-0.5 text-slate-800">{text}</p>
    </div>
  );
}
